spring:
  application:
    name: palantir
  cloud:
    stream:
      kafka:
        bindings:
          default:
            consumer:
              start-offers: latest
      bindings:
        userSearchRequest:
          destination: userSearchRequest
        userSearchResponse:
          destination: userSearchResponse
  kafka:
    bootstrap-servers: ${kafka_bootstrap_servers:localhost:9092}
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${kafka_username:'admin'} password=${kafka_password:'admin-secret'};
        mechanism: PLAIN
      security:
        protocol: SASL_PLAINTEXT
service:
  habr:
    url: https://habr.com/